### ISSUE TITLE
Footer text not centered

### ISSUE THREAD

**Issue by CruzedV** [GarageMakers/Ferma-hack#3]
Footer text misplaced, just lower it a bit

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please assign me this issue and attach a screenshot of changes needed

**Comment by DineshKoushik** [comment]
@himanshu007-creator , Hi I was trying to solve this issue, the footer was not in correct place, I tried with footer position as relative. That does make footer to come to bottom of page. But when we restore down the page, the footer is again misplaced. 

I'll create a PR, you can check what changes I have made and proceed accordingly.
Thank you

**Comment by CruzedV** [comment]
So, we already fix this. Commit in main. Thx everyone for attention!
